#!/bin/sh

original_clipboard=$(xclip -o)

echo $VIRTUAL_ENV | xclip

xdotool key ctrl+shift+n
sleep 1
wmctrl -i -a $(wmctrl -l |tail -n 1 | cut -d ' ' -f1)
xdotool type --delay 0.5 --clearmodifiers "source $(xclip -o)/bin/activate"
xdotool key Return;

echo $original_clipboard | xclip